
name: sync_to_doc

on:
  release:
    types: [published]
    branches: [master]

  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: merge master -> doc
        uses: devmasx/merge-branch@master
        with:
          github_token: ${{ github.token }}
          type: now
          from_branch: master
          target_branch: doc

